version: 0.0
os: linux

files:
  - source:  /
    destination: /root/community
    overwrite: yes

permissions:
  - object: /root/community
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root