spring.profiles.include=private

# jpa
spring.jpa.hibernate.ddl-auto=update

# db
spring.datasource.url= ${DB_URL}
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}

# redis
spring.data.redis.host= ${REDIS_URL}
spring.data.redis.port= ${REDIS_PORT}

# s3
cloud.aws.credentials.accessKey = ${IAM_ACCESS_KEY}
cloud.aws.credentials.secretKey = ${IAM_SECRET_KEY}
cloud.aws.s3.bucketName = ${S3_BUCKET_NAME}
cloud.aws.region.static = ${S3_REGION}
cloud.aws.s3.path = ${S3_URI}

# session cookie
server.servlet.session.cookie.path=/
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=3600

# spring session redis
spring.session.store-type=redis
spring.session.redis.namespace=community

logging.level.org.springframework.security = DEBUG